name: jobs sequence example workflow
on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print the job name
        run: echo ${{ github.job }}

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: print the job name
        run: echo ${{ github.job }}
    needs: job_1

  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: print the job name
        run: echo ${{ github.job }}
    needs: [job_1]

  job_4:
    runs-on: ubuntu-latest
    steps:
      - name: print the job name
        run: echo ${{ github.job }}
    needs:
      - job_2
      - job_3