name: First Workflow

on: # this workflow will be triggered once the main branch is pushed
  push:
    branches: [main]


jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:

      name: print a welcome message
      run: echo "Welcome to our first github actions workflow!"

      name: Checkout repository
      uses: actions/checkout@v4.2.2

      name: List repository files
      run: ls -la